import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}

export default function middleware(req: NextRequest) {
  const url = req.nextUrl
  
  // Get hostname of request (e.g. demo.vercel.pub, demo.localhost:3000)
  const hostname = req.headers.get('host') || 'localhost:3000'

  // Remove port if present for matching (e.g. localhost:3000 -> localhost)
  const hostnameWithoutPort = hostname.split(':')[0]

  // Define allowed domain base
  const allowedBaseDomains = [
    'localhost',
    '127.0.0.1',
    'app.offeriq.com',
    'builder.offeriq.com',
    'offeriq.com',
    'ofiq.app',
    'www.ofiq.app',
    'vercel.pub'
  ];

  // Check if it's a known domain exactly
  const isBaseDomain = allowedBaseDomains.includes(hostnameWithoutPort) || 
                       // Support preview URLs generated by Vercel
                       hostnameWithoutPort.endsWith('.vercel.app');

  if (!isBaseDomain) {
    // It's a custom domain or a subdomain (e.g., my-funnel.localhost or user1.domain.com)
    // Pass the original hostname without port to the dynamic route
    const domain = hostnameWithoutPort;
    
    // We rewrite to our dynamic sites route, preserving the pathname
    return NextResponse.rewrite(new URL(`/sites/${domain}${url.pathname}`, req.url))
  }

  return NextResponse.next()
}
