import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { createServerClient } from '@supabase/ssr'

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}

export default async function middleware(req: NextRequest) {
  const url = req.nextUrl

  // Get hostname of request (e.g. demo.vercel.pub, demo.localhost:3000)
  const hostname = req.headers.get('host') || 'localhost:3000'

  // Remove port if present for matching (e.g. localhost:3000 -> localhost)
  const hostnameWithoutPort = hostname.split(':')[0]

  // ── JVZoo sales domain (useofferiq.com) ──
  // This domain hosts the JVZoo funnel pages.
  // Route map:
  //   useofferiq.com/           → /jvzoo/fe        (Front-End offer)
  //   useofferiq.com/pro        → /jvzoo/pro        (OTO 1 – Pro)
  //   useofferiq.com/unlimited  → /jvzoo/unlimited  (OTO 2 – Unlimited)
  //   useofferiq.com/agency     → /jvzoo/agency     (OTO 3 – Agency)
  //   useofferiq.com/templates  → /jvzoo/templates  (OTO 4 – Templates)
  //   Legal pages pass through as-is.
  const jvzooDomains = ['useofferiq.com', 'www.useofferiq.com']
  if (jvzooDomains.includes(hostnameWithoutPort)) {
    const pathname = url.pathname

    // Legal / policy pages – serve from the main app unchanged
    const passthroughPaths = ['/terms', '/policy', '/refund']
    if (passthroughPaths.includes(pathname)) {
      return NextResponse.next()
    }

    // Map the incoming path to the /jvzoo/* route tree
    const jvzooRouteMap: Record<string, string> = {
      '/':           '/jvzoo/fe',
      '/pro':        '/jvzoo/pro',
      '/unlimited':  '/jvzoo/unlimited',
      '/agency':     '/jvzoo/agency',
      '/templates':  '/jvzoo/templates',
    }

    const destination = jvzooRouteMap[pathname]
    if (destination) {
      return NextResponse.rewrite(new URL(destination, req.url))
    }

    // Any other path on this domain → redirect to root (the FE page)
    return NextResponse.redirect(new URL('/', req.url))
  }

  // Define allowed domain base
  const allowedBaseDomains = [
    'localhost',
    '127.0.0.1',
    'useofferiq.com',
    'www.useofferiq.com',
    'app.offeriq.com',
    'builder.offeriq.com',
    'offeriq.com',
    'ofiq.app',
    'www.ofiq.app',
    'vercel.pub'
  ];

  // Check if it's a known domain exactly
  const isBaseDomain = allowedBaseDomains.includes(hostnameWithoutPort) ||
    // Support preview URLs generated by Vercel
    hostnameWithoutPort.endsWith('.vercel.app');

  // Create a response object to mutate
  let response = NextResponse.next({
    request: {
      headers: req.headers,
    },
  })

  // Create authenticated Supabase Client
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return req.cookies.getAll()
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => req.cookies.set(name, value))
          response = NextResponse.next({
            request: {
              headers: req.headers,
            },
          })
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          )
        },
      },
    }
  )

  // Refresh session if expired - required for Server Components
  const { data: { user } } = await supabase.auth.getUser()

  // Protect routes that require authentication
  const protectedRoutes = ['/builder', '/onboard']
  const authRoutes = ['/login', '/signup', '/verify-email']
  // /auth/invite must always be reachable — user lands here BEFORE the session cookie
  // is established (Supabase JS reads the hash client-side), so we never block it.
  const isInviteRoute = url.pathname.startsWith('/auth/invite')
  const isProtectedRoute = protectedRoutes.some(route => url.pathname.startsWith(route))
  const isAuthRoute = authRoutes.some(route => url.pathname.startsWith(route))

  if (isProtectedRoute && !user) {
    // Redirect to login if not authenticated
    return NextResponse.redirect(new URL('/login', req.url))
  }

  // Never bounce already-authenticated users away from /auth/invite
  // (they are mid-flow setting their password)
  if (isAuthRoute && user && !isInviteRoute) {
    // If they came from a pricing plan, send to checkout-now which will
    // check subscription status and redirect to billing settings if already subscribed.
    const plan = url.searchParams.get('plan');
    const dest = plan ? `/checkout-now?plan=${plan}` : '/';
    return NextResponse.redirect(new URL(dest, req.url));
  }

  if (!isBaseDomain) {
    // It's a custom domain or a subdomain (e.g., my-funnel.localhost or user1.domain.com)
    // Pass the original hostname without port to the dynamic route
    const domain = hostnameWithoutPort;

    // We rewrite to our dynamic sites route, preserving the pathname
    return NextResponse.rewrite(new URL(`/sites/${domain}${url.pathname}`, req.url))
  }

  return response
}