import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { createServerClient } from '@supabase/ssr'

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}

export default async function middleware(req: NextRequest) {
  const url = req.nextUrl

  // Get hostname of request (e.g. demo.vercel.pub, demo.localhost:3000)
  const hostname = req.headers.get('host') || 'localhost:3000'

  // Remove port if present for matching (e.g. localhost:3000 -> localhost)
  const hostnameWithoutPort = hostname.split(':')[0]

  // Define allowed domain base
  const allowedBaseDomains = [
    'localhost',
    '127.0.0.1',
    'app.offeriq.com',
    'builder.offeriq.com',
    'offeriq.com',
    'ofiq.app',
    'www.ofiq.app',
    'vercel.pub'
  ];

  // Check if it's a known domain exactly
  const isBaseDomain = allowedBaseDomains.includes(hostnameWithoutPort) ||
                       // Support preview URLs generated by Vercel
                       hostnameWithoutPort.endsWith('.vercel.app');

  // Create a response object to mutate
  let response = NextResponse.next({
    request: {
      headers: req.headers,
    },
  })

  // Create authenticated Supabase Client
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return req.cookies.getAll()
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => req.cookies.set(name, value))
          response = NextResponse.next({
            request: {
              headers: req.headers,
            },
          })
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          )
        },
      },
    }
  )

  // Refresh session if expired - required for Server Components
  const { data: { user } } = await supabase.auth.getUser()

  // Protect routes that require authentication
  const protectedRoutes = ['/workspaces', '/builder', '/onboard']
  const authRoutes = ['/login', '/signup', '/verify-email']
  const isProtectedRoute = protectedRoutes.some(route => url.pathname.startsWith(route))
  const isAuthRoute = authRoutes.some(route => url.pathname.startsWith(route))

  if (isProtectedRoute && !user) {
    // Redirect to login if not authenticated
    return NextResponse.redirect(new URL('/login', req.url))
  }

  if (isAuthRoute && user) {
    // Redirect to workspaces if already authenticated
    return NextResponse.redirect(new URL('/workspaces', req.url))
  }

  if (!isBaseDomain) {
    // It's a custom domain or a subdomain (e.g., my-funnel.localhost or user1.domain.com)
    // Pass the original hostname without port to the dynamic route
    const domain = hostnameWithoutPort;

    // We rewrite to our dynamic sites route, preserving the pathname
    return NextResponse.rewrite(new URL(`/sites/${domain}${url.pathname}`, req.url))
  }

  return response
}
