'use client';

import React from 'react';
import { motion } from 'framer-motion';

export interface FeatureTestimonialItem {
  id: string;
  name: string;
  role: string;
  content: string;
  avatarUrl: string;
}

export interface FeatureTestimonialsProps {
  headline?: string;
  testimonials?: FeatureTestimonialItem[];
  sectionId?: string;
  className?: string;
  style?: React.CSSProperties;
  elementStyles?: Record<string, React.CSSProperties>;
}

export function FeatureTestimonials({
  headline = 'Reviews that make us blush',
  testimonials = [
    {
      id: '1',
      name: 'Sarah Chen',
      role: 'Growth Lead @ StartupX',
      content: "This entirely changed how we look at our user retention. We saw a 40% improvement within two weeks. Absolutely indispensable.",
      avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d'
    },
    {
      id: '2',
      name: 'Marcus Bell',
      role: 'Founder @ ScaleIt',
      content: "I've tried every BI tool on the market. This is the first one that my non-technical team actually enjoys using every day.",
      avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704e'
    },
    {
      id: '3',
      name: 'Elena Silva',
      role: 'Head of Data @ Nexus',
      content: "The automated board reporting alone saves me ten hours a week. It pays for itself immediately.",
      avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704f'
    },
    {
      id: '4',
      name: 'David Okafor',
      role: 'Product Manager',
      content: "Fast, beautiful, and completely reliable. The API integration took less than five minutes.",
      avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704c'
    },
    {
      id: '5',
      name: 'Jessica Walsh',
      role: 'CEO @ Elevate',
      content: "We made our entire Q3 roadmap decisions using insights solely generated by this platform. Incredible value.",
      avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704a'
    },
    {
      id: '6',
      name: 'Alexei Rustov',
      role: 'VP Engineering',
      content: "The performance is unmatched. Even with massive datasets, the dashboards render in under a second.",
      avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704b'
    }
  ],
  sectionId = '',
  className = '',
  style = {},
  elementStyles = {},
}: FeatureTestimonialsProps) {
  return (
    <section
      id={sectionId || undefined}
      className={`w-full py-24 px-6 flex flex-col items-center bg-transparent scroll-mt-24 ${className}`}
      style={style}
    >
      <div className="flex flex-col items-center max-w-6xl w-full gap-16">
        
        {headline && (
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-50px' }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="text-4xl md:text-5xl lg:text-5xl font-bold tracking-tight text-foreground leading-[1.1] text-center max-w-2xl"
            style={elementStyles.headline}
          >
            {headline}
          </motion.h2>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
          {testimonials.map((item, idx) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 30, scale: 0.95 }}
              whileInView={{ opacity: 1, y: 0, scale: 1 }}
              viewport={{ once: true, margin: '-50px' }}
              transition={{ 
                duration: 0.6, 
                delay: (idx % 3) * 0.1, 
                type: 'spring', 
                stiffness: 100, 
                damping: 20 
              }}
              className="group flex flex-col justify-between p-8 rounded-3xl bg-card border border-border hover:border-primary/50 hover:bg-secondary/50 transition-all duration-300 gap-8 h-full shadow-sm"
              style={elementStyles[`card_${idx}`]}
            >
              <p 
                className="text-lg text-foreground/90 leading-relaxed font-medium"
                style={elementStyles[`card_${idx}_content`]}
              >
                "{item.content || (item as any).quote || (item as any).text || 'This entirely changed how we look at our user retention. Absolutely indispensable.'}"
              </p>

              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full overflow-hidden bg-secondary border border-border shrink-0 flex items-center justify-center text-muted-foreground font-bold">
                  <img 
                    src={item.avatarUrl || `https://i.pravatar.cc/150?u=${item.name.replace(/\s/g, '')}`} 
                    alt={item.name} 
                    className="w-full h-full object-cover grayscale opacity-90 group-hover:grayscale-0 group-hover:opacity-100 transition-all duration-300" 
                  />
                </div>
                <div className="flex flex-col">
                  <span 
                    className="text-sm font-semibold text-foreground tracking-tight"
                    style={elementStyles[`card_${idx}_name`]}
                  >
                    {item.name}
                  </span>
                  <span 
                    className="text-sm text-muted-foreground"
                    style={elementStyles[`card_${idx}_role`]}
                  >
                    {item.role}
                  </span>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

      </div>
    </section>
  );
}
